#!/usr/bin/env node

const yaml         = require('js-yaml');
const fs           = require('fs');
const rp           = require('request-promise');
const osmtogeojson = require('osmtogeojson');
const jsdom        = require('jsdom');

async function fetchDataFromOverpass() {
  const data = yaml.safeLoad(fs.readFileSync('data.yml', 'utf8'));

  let rate = Promise.resolve();

  const taxonomy = data.taxonomy;
  Object.keys(taxonomy).forEach((idCat) => {
    Object.keys(taxonomy[idCat].features).forEach((id) => {
      const { query } = taxonomy[idCat].features[id];
      const options = {
        method: 'POST',
        form: { data: `${data.config.query_search}${query}` },
        json: true,
      };
      rate = rate
        .then(() => rp('https://overpass.osmontrouge.fr/api/interpreter', options))
        .then(data => osmtogeojson(data))
        .then((geojson) => {
          fs.writeFileSync(`data/${id}.geojson`, JSON.stringify(geojson), 'utf-8');
          console.log(`${id} updated`);
        });
    });
  });
}
fetchDataFromOverpass();
