#!/usr/bin/env node

const yaml         = require('js-yaml');
const fs           = require('fs');
const rp           = require('request-promise');
const osmtogeojson = require('osmtogeojson');

const data = yaml.safeLoad(fs.readFileSync('data.yml', 'utf8'));

let rate = Promise.resolve();

Object.keys(data).forEach((idCat) => {
  Object.keys(data[idCat].features).forEach((id) => {
    const { query } = data[idCat].features[id];
    const options = {
      method: 'POST',
      form: { data: query },
      json: true,
    };
    rate = rate
      .then(() => rp('http://overpass-api.de/api/interpreter', options))
      .then((data) => {
        return osmtogeojson(data);
      })
      .then((geojson) => {
        fs.writeFileSync(`data/${id}.geojson`, JSON.stringify(geojson), 'utf-8');
        console.log(`${id} updated`);
      });
  });
});
